[theme]
primaryColor = "#272E61"
backgroundColor = "#D0DAD8"
secondaryBackgroundColor = "#D3D3D3"
textColor = "#272E61"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"